version: 2.1
orbs: 
  cypress: cypress-io/cypress@1

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - cypress
jobs:
  run-tests:
    docker:
      - image: 'cypress/base:12'
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: Installing dependencies
          command: 'npm install'
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: 
          name: App in the background
          command: 'npm start'
          background: true
      - run: 
          name: Wait for localhost to load
          command: 'npm wait-on http://localhost:3000'
      - run:
          name: "Runing tests"
          command: npx cypress run --record --key $CYPRESS_RECORD_KEY