version: 2.1

workflows:
  my-workflow:
    jobs:
      - check-env:
          context:
            - cypress
      - run-tests:
          context:
            - cypress
jobs:
  check-env:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Check cypress key"
          command: echo $CYPRESS_RECORD_KEY
  run-tests:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: 
          name: App in the background
          command: 'npm start'
          background: true
      - run: 
          name: Wait for localhost to load
          command: 'npm wait-on http://localhost:3000'
      - run:
          name: "Runing tests"
          command: $(npm bin)/cypress run --record --key $CYPRESS_RECORD_KEY