version: 2.1

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - cypress

jobs:
  run-tests:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo environment variables from org-global context"
          command: echo $CYPRESS_RECORD_KEY