environment: 
  CYPRESS_RECORD_KEY: 17b5dc8d-e63d-4640-8ab9-ec38c81d1d1e
orbs: 
  cypress: cypress-io/cypress@1
version: 2.1
workflows: 
  build: 
    jobs: 
      - 
        cypress/install: 
          build: "npm run build"
      - 
        cypress/run: 
          post-steps: 
            - 
              store_test_results: 
                path: cypress/results
          record: true
          requires: 
            - cypress/install
          start: "npm start"
